### ISSUE TITLE
Visual cue for text linking to a page

### ISSUE THREAD

**Issue by neeraj-lad** [aviaryan/resume#5]
It would be great if there is visual cue for text linking to a different page (like blue text links in Bootstrap).

**Comment by aviaryan** [comment]
Hi. Thanks for the issue.
I have provided _visual cue_ for links in the projects and work section. 
As far as the links in the 'profiles' and 'contact' section is concerned, it is quite obvious that twitter and fb usernames might be linking to the user profile pages. So I chose not to include any visual cue as it will add to clutter. 

I want to make this resume printable so I won't add any hyperlinks with random hypertexts. Hypertexts shall either be full web url's or self-describing text (like github username).

Which links were you talking about in particular ?

**Comment by neeraj-lad** [comment]
I was talking about the profile links. 

You might wish to add some hover effects at-least, since it seems a bit atypical currently, and a novice user might easily miss the links, due to the absence of a typical visual cue.

**Comment by aviaryan** [comment]
The page's design philosophy is plain and static. I don't want to break it by animations and stuff. Do you have something in mind that can be done here ?

**Comment by neeraj-lad** [comment]
Nothing fancy tbh. If you could style your profile links similar to the GitHub links (which are blue in color), it would be great. You can color them in a different tint of black if you wish to. My concern was that most people would miss those links, since they are styled similar to the text.

**Comment by aviaryan** [comment]
Links already have underlines as visual cues. Hence closing.
